#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🔧💣 Lagi ngerakit, ngetes, sama ngebuild project sebelum commit...'

# Cek format pakai Prettier
pnpm check-format ||
(
  echo '💩🚽 Formatting lo jorok kayak wc umum. 💩🚽
      Prettier Check GAGAL. Jalanin "pnpm format", benerin dulu, baru commit sono.'
  false;
)

# Cek type check dari tsconfig
pnpm check-types ||
(
  echo '🤡🧠 Type checknya MAMPUS. 🤡🧠
      Lo yakin mau pamerin kode sampah kayak gitu? Benerin napa.'
  false;
)

# Build project
pnpm build ||
(
  echo '🔥🗑️ BUILD LO KEBARAKAN, BRO. 🔥🗑️
      Error segitu aja ga kelar-kelar. Fix dulu, baru nyusahin repo.'
  false;
)

# Kalau semua lolos
echo '🏆😎 Sip, project lo lolos audit kali ini. Commit lanjut! 🏆😎'
